trigger: none
pr: none

variables:
  tfImports:
    - resourceGroup:
        address: module.rg.azurerm_resource_group.rg
        id: /subscriptions/1111111-1111-1111-1111-111111111111/resourceGroups/invreporting-prod-eastus

jobs:
- job: TEST
  steps:
    - checkout: none
    - ${{ each resource in variables['tfImports'] }}:
      - bash: echo $address; echo $id
        env:
          address: ${{ resource.key }}
          id: ${{ resource.value }}
          