trigger: none
pr: none

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: echo "##vso[task.setvariable variable=TEST;isOutput=true]false"
      name: A1S
- stage: B
  dependsOn: A
  variables: 
    VAR: $[ stageDependencies.A.A1.outputs['A1S.TEST'] ]
  jobs:
    - job: B1
      steps:
      - bash: echo $(VAR)

