trigger: none
pr: none

parameters:
  - name: SPLITS
    type: object
    default:
      - Step: 1
        NonProd: 1
        Prod: 99
      - Step: 2
        NonProd: 50
        Prod: 50

stages:
- stage: Init
  jobs:
    - job: init
      steps:
        - script: echo hi

- ${{ each split in parameters.SPLITS }}:
  - stage: A${{split.Step}}
    dependsOn:
      - Init
      - ${{ if ne(split.Step, 1)}}:
        - A${{ split.Step - 1 }}
    jobs:
    - job: A${{split.Step}}
      steps:
      - script: |
          echo ${{ split.Step }}
          echo ${{ split.Prod }}
          echo ${{ split.NonProd }}

