trigger: none
pr: none

parameters:
  - name: PARALLELISM
    displayName: Number of instances to deploy to simultaneously
    type: number
    default: 1

  - name: LEGACY_INSTANCES
    displayName: Legacy instances to deploy to
    type: object
    default: {
      "Instance 001": { ID: "001" },
      "Instance 002": { ID: "002" },
      "Instance 103": { ID: "103" },
      "Instance 004": { ID: "004" }
    }

stages:
- stage: Init
  jobs:
  - job: Deploy
    strategy:
      matrix: ${{ parameters.LEGACY_INSTANCES }}
      maxParallel: ${{ parameters.PARALLELISM }}
    steps:
      - script: echo $(ID)
        displayName: Deploy $(ID)