trigger: none
pr: none

variables:
  SPLITS:
    - Step: 1
      NonProd: 1
      Prod: 99
    - Step: 2
      NonProd: 50
      Prod: 50

stages:
- ${{ each split in variables.SPLITS }}:
  - stage: A${{split.Step}}
    jobs:
    - job: A${{split.Step}}
      steps:
      - script: |
          echo ${{ split.Step }}
          echo ${{ split.Prod }}
          echo ${{ split.NonProd }}

