trigger: none
pr: none

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: echo "##vso[task.setvariable variable=TEST;isOutput=true]false"
      name: A1S
- stage: B
  dependsOn: A
  condition: eq(dependencies.A.outputs['A1.A1S.TEST'], true)
  jobs:
    - job: B1
      steps:
      - bash: echo "Hello World"

